### ISSUE TITLE
NPE when switching to a profile without QH installed

### ISSUE THREAD

**Issue by raiyni** [Zoinkwiz/quest-helper#1564]
```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:372)
	at java.base/java.util.List.of(List.java:807)
	at com.questhelper.helpers.miniquests.alfredgrimhandsbarcrawl.AlfredGrimhandsBarcrawl.getItemRequirements(AlfredGrimhandsBarcrawl.java:201)
	at com.questhelper.managers.QuestManager.lambda$getAllItemRequirements$8(QuestManager.java:482)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.questhelper.managers.QuestManager.lambda$getAllItemRequirements$9(QuestManager.java:481)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:228)
	at client.cc(client.java:8589)
	at client.bh(client.java)
	at bx.aa(bx.java:380)
	at bx.kn(bx.java)
	at bx.run(bx.java:11548)```

**Comment by pajlada** [comment]
Bit of a trickier thing to reproduce since running Quest Helper in IntelliJ will "force" install Quest Helper.
When trying this on the standard client, I only found https://github.com/Zoinkwiz/quest-helper/pull/1565 but I didn't run into any other NPE
