### ISSUE TITLE
Plugin fails to set up quest/diary listing on startup

### ISSUE THREAD

**Issue by Nightfirecat** [Zoinkwiz/quest-helper#1633]
```
2024-07-11 15:25:27 PDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.AssertionError: null
	at com.questhelper.requirements.item.ItemRequirements.<init>(ItemRequirements.java:72)
	at com.questhelper.helpers.quests.royaltrouble.RoyalTrouble.setupRequirements(RoyalTrouble.java:232)
	at com.questhelper.questhelpers.QuestHelper.initializeRequirements(QuestHelper.java:255)
	at com.questhelper.managers.QuestManager.setupRequirements(QuestManager.java:549)
	at com.questhelper.QuestHelperPlugin.lambda$startUp$0(QuestHelperPlugin.java:233)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.fy(client.java:6507)
	at client.bw(client.java)
	at bs.ar(bs.java:388)
	at bs.jg(bs.java)
	at bs.run(bs.java:7916)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Zoinkwiz** [comment]
This should hopefully have been resolved with https://github.com/Zoinkwiz/quest-helper/commit/831819fe4f6f3f2aae4512e9d62ebf7c009529cc, which should be live now
