### ISSUE TITLE
Quest Helper not loading in RuneLite

### ISSUE THREAD

**Issue by LambChopSoldier** [Zoinkwiz/quest-helper#734]
I've been having an issue with Quest Helper plugin not working in RuneLite. The icon isn't even showing on the sidebar. I've uninstalled/reinstalled the plugin multiple times, I've even relogged and restarted RuneLite as well. It's just not working anymore. I've attached my client log already because I just have a feeling it would be asked for. 

[client.log](https://github.com/Zoinkwiz/quest-helper/files/8237279/client.log)
)

**Comment by Ctony92** [comment]
I am also having the same issue. I have ran through all troubleshooting shy of coding. Uninstalled and reinstalled quest helper plugin and runelite, signed out and back in, imported signed out settings to reset and reinstalled quest helper. Still quest helper does not appear on my sidebar.

**Comment by Nightfirecat** [comment]
From your logs:
```
2022-03-12 01:59:31 [pool-3-thread-1] ERROR n.r.c.e.ExternalPluginManager - Unable to download external plugin "quest-helper"
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:409)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at okhttp3.internal.cache.CacheInterceptor$1.read(CacheInterceptor.java:175)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at net.runelite.client.util.CountingInputStream.read(CountingInputStream.java:47)
	at com.google.common.hash.HashingInputStream.read(HashingInputStream.java:67)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
	at com.google.common.io.ByteSink.writeFrom(ByteSink.java:126)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:241)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Check your internet connection.

**Comment by Ctony92** [comment]
Hey, I'm a little rusty with the script language. I see the error due to
time out and you say to check my connection but my connection is fine and
runelite loads and plays fine. I am able to use all other plugins except
for quest helper?

**Comment by Nightfirecat** [comment]
The issue is RuneLite isn't able to access `https://repo.runelite.net/` to download that plugin, due to timing out during that connection. idk if your connection is slow, or experiencing some other issue, but something is up which is causing that timeout.
