### ISSUE TITLE
Using quest helper and sometimes client freezes and crashes.

### ISSUE THREAD

**Issue by stringyjosh94** [Zoinkwiz/quest-helper#765]
Snippet from log file, not sure if it's related.

2022-04-20 12:55:18 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2022-04-20 12:56:06 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at com.questhelper.steps.DetailedQuestStep.renderInventory(DetailedQuestStep.java:446)
	at com.questhelper.steps.DetailedQuestStep.makeWidgetOverlayHint(DetailedQuestStep.java:345)
	at com.questhelper.overlays.QuestHelperWidgetOverlay.render(QuestHelperWidgetOverlay.java:60)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:755)

**Comment by csauce** [comment]
[client_2022-04-27.0.log](https://github.com/Zoinkwiz/quest-helper/files/8580408/client_2022-04-27.0.log)

similar issue

**Comment by Zoinkwiz** [comment]
This should be resolved now.
