### ISSUE TITLE
Pirate's Treasure

### ISSUE THREAD

**Issue by everheartproductions** [Zoinkwiz/quest-helper#886]
After giving Frank the Karmaja Rum, there's no more prompts - need to go to varrock blue moon inn yet, loot the chest upstairs, tele to falador, and dig in garden. 

Correction - after diggin in falador, it seems the prompts came back.

Issue: prompts seem to disappear after giving frank his rum, but prompts reappear after visiting falador garden & digging.

**Comment by Adam-** [comment]
Can reproduce:

```
2023-09-07 16:27:27 EDT [Client] DEBUG client-patch - Chat message type DIALOG: Redbeard Frank|Have ye brought some rum for yer ol' mate Frank?
2023-09-07 16:27:28 EDT [Client] DEBUG client-patch - Chat message type DIALOG: RuneLite|Yes, I've got some.
2023-09-07 16:27:28 EDT [Client] DEBUG client-patch - Chat message type DIALOG: Redbeard Frank|Now a deal's a deal, I'll tell ye about the treasure. I used to serve under a pirate captain called One-Eyed Hector.
2023-09-07 16:27:29 EDT [Client] DEBUG client-patch - Chat message type DIALOG: Redbeard Frank|Hector were very successful and became very rich. But about a year ago we were boarded by the Customs and Excise Agents.
2023-09-07 16:27:29 EDT [Client] DEBUG client-patch - Chat message type DIALOG: Redbeard Frank|Hector were killed along with many of the crew, I were one of the few to escape and I escaped with this.
2023-09-07 16:27:29 EDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.questhelper.requirements.ZoneRequirement.lambda$check$0(ZoneRequirement.java:102)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.questhelper.requirements.ZoneRequirement.check(ZoneRequirement.java:102)
	at com.questhelper.requirements.conditional.Conditions.lambda$check$0(Conditions.java:126)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:605)
	at com.questhelper.requirements.conditional.Conditions.check(Conditions.java:127)
	at com.questhelper.steps.ConditionalStep.updateSteps(ConditionalStep.java:260)
	at com.questhelper.steps.ConditionalStep.startUp(ConditionalStep.java:179)
	at com.questhelper.questhelpers.QuestHelper.startUpStep(QuestHelper.java:130)
	at com.questhelper.questhelpers.BasicQuestHelper.updateQuest(BasicQuestHelper.java:75)
	at com.questhelper.QuestHelperPlugin.onVarbitChanged(QuestHelperPlugin.java:458)
```

**Comment by kcjg94** [comment]
![image](https://github.com/user-attachments/assets/9692b739-59ee-4789-b2f4-a1945b5db94a)

I didn't have this issue.
